"""empty message

Revision ID: c00e386dec24
Revises: 
Create Date: 2018-11-10 22:42:59.613740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c00e386dec24'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('NODES')
    op.drop_table('SHOPS')
    op.drop_table('TOURISM')
    op.drop_table('AMENITIES')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AMENITIES',
    sa.Column('NODE_ID', sa.INTEGER(), nullable=True),
    sa.Column('DESCRIPTION', sa.TEXT(), nullable=True),
    sa.Column('TYPE', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['NODE_ID'], ['NODES.NODE_ID'], )
    )
    op.create_table('TOURISM',
    sa.Column('NODE_ID', sa.INTEGER(), nullable=True),
    sa.Column('DESCRIPTION', sa.TEXT(), nullable=True),
    sa.Column('TYPE', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['NODE_ID'], ['NODES.NODE_ID'], )
    )
    op.create_table('SHOPS',
    sa.Column('NODE_ID', sa.INTEGER(), nullable=True),
    sa.Column('TYPE', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['NODE_ID'], ['NODES.NODE_ID'], )
    )
    op.create_table('NODES',
    sa.Column('NODE_ID', sa.INTEGER(), nullable=False),
    sa.Column('IMAGE_LINK', sa.TEXT(), nullable=True),
    sa.Column('WEBSITE', sa.TEXT(), nullable=True),
    sa.Column('LON', sa.REAL(), nullable=True),
    sa.Column('LAT', sa.REAL(), nullable=True),
    sa.Column('DESCRIPTION', sa.TEXT(), nullable=True),
    sa.Column('PHONE', sa.TEXT(), nullable=True),
    sa.Column('EMAIL', sa.TEXT(), nullable=True),
    sa.Column('NAME', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('NODE_ID')
    )
    # ### end Alembic commands ###
